name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev glibc-source libidn-dev libidn12
          haxelib setup ~/haxelib
          haxelib install hmm
          haxelib run hmm setup
          haxelib run hmm install
          haxelib install hxvlc 2.2.6
          haxelib git polymod https://github.com/froncekmatthew173-bot/polymod-dnb.git main
          haxelib list

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id }}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxBuild
          path: export/release/linux/bin

  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Haxe Path
        run: |
          setx HAXEPATH "C:\HaxeToolkit\haxe"
          setx PATH "%HAXEPATH%;%PATH%"

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hmm
          haxelib run hmm setup
          haxelib run hmm install
          haxelib install hxvlc 2.2.6
          haxelib list

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id }}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin

  buildMac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm
          haxelib run hmm setup
          haxelib run hmm install
          haxelib install hxvlc 2.2.6
          haxelib git polymod https://github.com/froncekmatthew173-bot/polymod-dnb.git main
          haxelib list

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id }}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macBuild
          path: export/release/macos/bin

  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Dependencies
        run: |
          haxelib install hmm
          haxelib run hmm setup
          haxelib run hmm install
          haxelib install hxvlc 2.2.6
          haxelib git polymod https://github.com/froncekmatthew173-bot/polymod-dnb.git main
          haxelib run lime setup android --accept
          haxelib list

      - name: Build Android ARM64
        run: haxelib run lime build android -final -Dandroid-arm64

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-ARM64
          path: export/android/bin/app/build/outputs/**/*.apk

  buildIos:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Dependencies
        run: |
          haxelib install hmm
          haxelib run hmm setup
          haxelib run hmm install
          haxelib git polymod https://github.com/froncekmatthew173-bot/polymod-dnb.git main
          haxelib install hxvlc 2.2.6
          haxelib list

      - name: Build iOS (Device)
        run: haxelib run lime build ios -final -Dios-device

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-arm64
          path: export/ios/build/**/*.ipa
